// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using demoCatalogue.Data;

namespace demoCatalogue.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20210125114305_GiaoVien")]
    partial class GiaoVien
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("demoCatalogue.Models.GiaoVien", b =>
                {
                    b.Property<string>("MaGiaoVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhoaGiaoVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGiaoVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TuoiGiaoVien")
                        .HasColumnType("int");

                    b.HasKey("MaGiaoVien");

                    b.ToTable("GiaoVien");
                });

            modelBuilder.Entity("demoCatalogue.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenSinhVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TuoiSinhVien")
                        .HasColumnType("int");

                    b.HasKey("MaSinhVien");

                    b.ToTable("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
